// Code generated by go-enum DO NOT EDIT.
// Version: 0.6.0
// Revision: 919e61c0174b91303753ee3898569a01abb32c97
// Build Date: 2023-12-18T15:54:43Z
// Built By: goreleaser

package enums

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strconv"
)

const (
	// UserRoleAdmin is a UserRole of type admin.
	UserRoleAdmin UserRole = "admin"
	// UserRoleMember is a UserRole of type member.
	UserRoleMember UserRole = "member"
)

var ErrInvalidUserRole = errors.New("not a valid UserRole")

// String implements the Stringer interface.
func (x UserRole) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UserRole) IsValid() bool {
	_, err := ParseUserRole(string(x))
	return err == nil
}

var _UserRoleValue = map[string]UserRole{
	"admin":  UserRoleAdmin,
	"member": UserRoleMember,
}

// ParseUserRole attempts to convert a string to a UserRole.
func ParseUserRole(name string) (UserRole, error) {
	if x, ok := _UserRoleValue[name]; ok {
		return x, nil
	}
	return UserRole(""), fmt.Errorf("%s is %w", name, ErrInvalidUserRole)
}

// MarshalText implements the text marshaller method.
func (x UserRole) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *UserRole) UnmarshalText(text []byte) error {
	tmp, err := ParseUserRole(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

var errUserRoleNilPtr = errors.New("value pointer is nil") // one per type for package clashes

var sqlIntUserRoleMap = map[int64]UserRole{
	1: UserRoleAdmin,
	2: UserRoleMember,
}

var sqlIntUserRoleValue = map[UserRole]int64{
	UserRoleAdmin:  1,
	UserRoleMember: 2,
}

func lookupSqlIntUserRole(val int64) (UserRole, error) {
	x, ok := sqlIntUserRoleMap[val]
	if !ok {
		return x, fmt.Errorf("%v is not %w", val, ErrInvalidUserRole)
	}
	return x, nil
}

// Scan implements the Scanner interface.
func (x *UserRole) Scan(value interface{}) (err error) {
	if value == nil {
		*x = UserRole("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x, err = lookupSqlIntUserRole(v)
	case string:
		*x, err = ParseUserRole(v)
	case []byte:
		if val, verr := strconv.ParseInt(string(v), 10, 64); verr == nil {
			*x, err = lookupSqlIntUserRole(val)
		} else {
			// try parsing the value as a string
			*x, err = ParseUserRole(string(v))
		}
	case UserRole:
		*x = v
	case int:
		*x, err = lookupSqlIntUserRole(int64(v))
	case *UserRole:
		if v == nil {
			return errUserRoleNilPtr
		}
		*x = *v
	case uint:
		*x, err = lookupSqlIntUserRole(int64(v))
	case uint64:
		*x, err = lookupSqlIntUserRole(int64(v))
	case *int:
		if v == nil {
			return errUserRoleNilPtr
		}
		*x, err = lookupSqlIntUserRole(int64(*v))
	case *int64:
		if v == nil {
			return errUserRoleNilPtr
		}
		*x, err = lookupSqlIntUserRole(int64(*v))
	case float64: // json marshals everything as a float64 if it's a number
		*x, err = lookupSqlIntUserRole(int64(v))
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errUserRoleNilPtr
		}
		*x, err = lookupSqlIntUserRole(int64(*v))
	case *uint:
		if v == nil {
			return errUserRoleNilPtr
		}
		*x, err = lookupSqlIntUserRole(int64(*v))
	case *uint64:
		if v == nil {
			return errUserRoleNilPtr
		}
		*x, err = lookupSqlIntUserRole(int64(*v))
	case *string:
		if v == nil {
			return errUserRoleNilPtr
		}
		*x, err = ParseUserRole(*v)
	default:
		return errors.New("invalid type for UserRole")
	}

	return
}

// Value implements the driver Valuer interface.
func (x UserRole) Value() (driver.Value, error) {
	val, ok := sqlIntUserRoleValue[x]
	if !ok {
		return nil, ErrInvalidUserRole
	}
	return int64(val), nil
}
